/**
 * A real, openable PDF for the sample student profile.
 *
 * The demo profile used to carry { fileName: "Aarav_Sharma_Resume_2026.pdf", dataUrl: "#" },
 * which rendered a "View resume" link that could never open anything — clicking it
 * navigated to "#" and looked like the page had reloaded. A sample profile that
 * advertises a document has to actually hold one, so this is a genuine (small,
 * single-page) PDF rather than a placeholder.
 */

export const SAMPLE_RESUME_FILENAME = "Aarav_Sharma_Resume_2026.pdf";

export const SAMPLE_RESUME_DATA_URL =
  "data:application/pdf;base64," +
  "JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwg" +
  "L1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2Ug" +
  "L1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA1OTUgODQyXSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA1IDAg" +
  "UiA+PiA+PiAvQ29udGVudHMgNCAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCAxNDYzID4+CnN0cmVhbQpC" +
  "VCAvRjEgMjAgVGYgNjAgNzYyIFRkIChBYXJhdiBTaGFybWEpIFRqIEVUCkJUIC9GMSAxMCBUZiA2MCA3NDQgVGQgKEJB" +
  "TVMgLSBCYWNoZWxvciBvZiBBeXVydmVkaWMgTWVkaWNpbmUgJiBTdXJnZXJ5ICB8ICBBbGwgSW5kaWEgSW5zdGl0dXRl" +
  "IG9mIEF5dXJ2ZWRhIChBSUlBKSwgTmV3IERlbGhpKSBUaiBFVApCVCAvRjEgMTAgVGYgNjAgNzMwIFRkIChOZXcgRGVs" +
  "aGkgIHwgIGRlbW8uc3R1ZGVudEBzZXR1LmRldikgVGogRVQKMC40MiAwLjQ5IDAuMjQgcmcgNjAgNzIwIG0gNTM1IDcy" +
  "MCBsIDUzNSA3MjIgbCA2MCA3MjIgbCBmCkJUIC9GMSAxMiBUZiA2MCA2OTQgVGQgKFNVTU1BUlkpIFRqIEVUCkJUIC9G" +
  "MSAxMCBUZiA2MCA2NzggVGQgKEZpbmFsLXllYXIgQkFNUyBpbnRlcm4gZm9jdXNlZCBvbiBLYXlhY2hpa2l0c2EgYW5k" +
  "IFBhbmNoYWthcm1hLCB3aXRoIHJvdGF0aW9ucyBpbiBhIE5BQkgtYWNjcmVkaXRlZCkgVGogRVQKQlQgL0YxIDEwIFRm" +
  "IDYwIDY2NCBUZCAoQXl1cnZlZGEgaG9zcGl0YWwsIGEgQ1RSSS1yZWdpc3RlcmVkIGNsaW5pY2FsIHN0dWR5IGFuZCBh" +
  "biBlU2FuamVldmFuaS1BWVVTSCB0ZWxlY29uc3VsdGF0aW9uIGh1Yi4pIFRqIEVUCkJUIC9GMSAxMiBUZiA2MCA2MzQg" +
  "VGQgKFNLSUxMUykgVGogRVQKQlQgL0YxIDEwIFRmIDYwIDYxOCBUZCAoTmFkaSBQYXJpa3NoYSwgUHJha3JpdGkgQXNz" +
  "ZXNzbWVudCwgUGFuY2hha2FybWEsIENhc2UgVGFraW5nLCBJQ0gtR0NQLCBCaW9zdGF0aXN0aWNzLCBlU2FuamVldmFu" +
  "aS1BWVVTSCkgVGogRVQKQlQgL0YxIDEyIFRmIDYwIDU4OCBUZCAoRVhQRVJJRU5DRSkgVGogRVQKQlQgL0YxIDEwIFRm" +
  "IDYwIDU3MiBUZCAoQ2xpbmljYWwgUmVzZWFyY2ggSW50ZXJuIC0gQXl1cnZlZGEgVHJpYWxzLCBEYWJ1ciBSZXNlYXJj" +
  "aCBGb3VuZGF0aW9uICAtLSAgMjAyNSkgVGogRVQKQlQgL0YxIDEwIFRmIDYwIDU1OCBUZCAoRHJhZnRlZCBDUkZzIGZv" +
  "ciBhIG11bHRpLWNlbnRyZSB0cmlhbCBhbmQgc3VwcG9ydGVkIENUUkkgcmVnaXN0cmF0aW9uIGFuZCBhZHZlcnNlLWV2" +
  "ZW50IHJlcG9ydGluZy4pIFRqIEVUCkJUIC9GMSAxMiBUZiA2MCA1MjggVGQgKEVEVUNBVElPTikgVGogRVQKQlQgL0Yx" +
  "IDEwIFRmIDYwIDUxMiBUZCAoQkFNUywgQWxsIEluZGlhIEluc3RpdHV0ZSBvZiBBeXVydmVkYSAoQUlJQSksIE5ldyBE" +
  "ZWxoaSwgMjAyMyAtIDIwMjgpIFRqIEVUCkJUIC9GMSAxMiBUZiA2MCA0ODIgVGQgKENFUlRJRklDQVRJT05TKSBUaiBF" +
  "VApCVCAvRjEgMTAgVGYgNjAgNDY2IFRkIChZQ0IgWW9nYSBQcm90b2NvbCBJbnN0cnVjdG9yLCBMZXZlbCAxICgyMDI1" +
  "KTsgR29vZCBDbGluaWNhbCBQcmFjdGljZSBmb3IgQVlVU0ggVHJpYWxzLCBDQ1JBUyAoMjAyNCkpIFRqIEVUCkJUIC9G" +
  "MSA4IFRmIDYwIDkwIFRkIChTYW1wbGUgZG9jdW1lbnQgZ2VuZXJhdGVkIGZvciB0aGUgU2tpbGwgU2V0dSBkZW1vIHBy" +
  "b2ZpbGUuKSBUaiBFVAplbmRzdHJlYW0KZW5kb2JqCjUgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUx" +
  "IC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iagp4cmVmCjAgNgowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAw" +
  "MDkgMDAwMDAgbiAKMDAwMDAwMDA1OCAwMDAwMCBuIAowMDAwMDAwMTE1IDAwMDAwIG4gCjAwMDAwMDAyNDEgMDAwMDAg" +
  "biAKMDAwMDAwMTc1NiAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDYgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjE4" +
  "MjYKJSVFT0Y=";
