/**
 * A real, openable PDF for the sample student profile.
 *
 * The demo profile used to carry { fileName: "Aarav_Sharma_Resume_2026.pdf", dataUrl: "#" },
 * which rendered a "View resume" link that could never open anything — clicking it
 * navigated to "#" and looked like the page had reloaded. A sample profile that
 * advertises a document has to actually hold one, so this is a genuine (small,
 * single-page) PDF rather than a placeholder.
 */

export const SAMPLE_RESUME_FILENAME = "Aarav_Sharma_Resume_2026.pdf";

export const SAMPLE_RESUME_DATA_URL =
  "data:application/pdf;base64," +
  "JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwg" +
  "L1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2Ug" +
  "L1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA1OTUgODQyXSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA1IDAg" +
  "UiA+PiA+PiAvQ29udGVudHMgNCAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCAxMzY5ID4+CnN0cmVhbQpC" +
  "VCAvRjEgMjAgVGYgNjAgNzYyIFRkIChBYXJhdiBTaGFybWEpIFRqIEVUCkJUIC9GMSAxMCBUZiA2MCA3NDQgVGQgKEIu" +
  "VGVjaCBDb21wdXRlciBTY2llbmNlICYgRW5naW5lZXJpbmcgIHwgIEFwZXggVW5pdmVyc2l0eSBvZiBUZWNobm9sb2d5" +
  "ICYgQXBwbGllZCBTY2llbmNlcykgVGogRVQKQlQgL0YxIDEwIFRmIDYwIDczMCBUZCAoQmVuZ2FsdXJ1LCBLYXJuYXRh" +
  "a2EgIHwgIGRlbW8uc3R1ZGVudEBzZXR1LmRldikgVGogRVQKMC40MiAwLjQ5IDAuMjQgcmcgNjAgNzIwIG0gNTM1IDcy" +
  "MCBsIDUzNSA3MjIgbCA2MCA3MjIgbCBmCkJUIC9GMSAxMiBUZiA2MCA2OTQgVGQgKFNVTU1BUlkpIFRqIEVUCkJUIC9G" +
  "MSAxMCBUZiA2MCA2NzggVGQgKEZpbmFsLXllYXIgQ1NFIHVuZGVyZ3JhZHVhdGUgZm9jdXNlZCBvbiBmdWxsLXN0YWNr" +
  "IGFyY2hpdGVjdHVyZSwgZGlzdHJpYnV0ZWQgY2xvdWQpIFRqIEVUCkJUIC9GMSAxMCBUZiA2MCA2NjQgVGQgKHN5c3Rl" +
  "bXMgYW5kIGFwcGxpZWQgbWFjaGluZSBsZWFybmluZy4gQnVpbHQgYW5kIHNoaXBwZWQgcHJvZHVjdGlvbiBtaWNyb3Nl" +
  "cnZpY2VzLikgVGogRVQKQlQgL0YxIDEyIFRmIDYwIDYzNCBUZCAoU0tJTExTKSBUaiBFVApCVCAvRjEgMTAgVGYgNjAg" +
  "NjE4IFRkIChSZWFjdCwgTm9kZS5qcywgVHlwZVNjcmlwdCwgUHl0aG9uLCBTUUwsIEFXUywgRG9ja2VyLCBEYXRhIFN0" +
  "cnVjdHVyZXMgJiBBbGdvcml0aG1zKSBUaiBFVApCVCAvRjEgMTIgVGYgNjAgNTg4IFRkIChFWFBFUklFTkNFKSBUaiBF" +
  "VApCVCAvRjEgMTAgVGYgNjAgNTcyIFRkIChTb2Z0d2FyZSBFbmdpbmVlcmluZyBJbnRlcm4sIEFwZXggR2xvYmFsIFRl" +
  "Y2hub2xvZ2llcyAgLS0gIDIwMjUpIFRqIEVUCkJUIC9GMSAxMCBUZiA2MCA1NTggVGQgKFNoaXBwZWQgdGhyZWUgY3Vz" +
  "dG9tZXItZmFjaW5nIGZlYXR1cmVzIGFuZCBjdXQgQVBJIHA5NSBsYXRlbmN5IGJ5IDQwIHBlcmNlbnQuKSBUaiBFVApC" +
  "VCAvRjEgMTIgVGYgNjAgNTI4IFRkIChFRFVDQVRJT04pIFRqIEVUCkJUIC9GMSAxMCBUZiA2MCA1MTIgVGQgKEIuVGVj" +
  "aCBDU0UsIEFwZXggVW5pdmVyc2l0eSBvZiBUZWNobm9sb2d5ICYgQXBwbGllZCBTY2llbmNlcywgMjAyMyAtIDIwMjcp" +
  "IFRqIEVUCkJUIC9GMSAxMiBUZiA2MCA0ODIgVGQgKENFUlRJRklDQVRJT05TKSBUaiBFVApCVCAvRjEgMTAgVGYgNjAg" +
  "NDY2IFRkIChBV1MgQ2VydGlmaWVkIENsb3VkIFByYWN0aXRpb25lciAoMjAyNSk7IEFkdmFuY2VkIERhdGEgU3RydWN0" +
  "dXJlcyAmIEFsZ29yaXRobXMsIE5QVEVMICgyMDI0KSkgVGogRVQKQlQgL0YxIDggVGYgNjAgOTAgVGQgKFNhbXBsZSBk" +
  "b2N1bWVudCBnZW5lcmF0ZWQgZm9yIHRoZSBTa2lsbCBTZXR1IGRlbW8gcHJvZmlsZS4pIFRqIEVUCmVuZHN0cmVhbQpl" +
  "bmRvYmoKNSAwIG9iago8PCAvVHlwZSAvRm9udCAvU3VidHlwZSAvVHlwZTEgL0Jhc2VGb250IC9IZWx2ZXRpY2EgPj4K" +
  "ZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAw" +
  "MDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDI0MSAwMDAwMCBuIAowMDAwMDAxNjYyIDAwMDAwIG4gCnRy" +
  "YWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKMTczMgolJUVPRg==";
